# Generated by Django 4.2.17 on 2025-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0022_alter_campaign_current_amount_alter_campaign_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hederauser',
            name='nonce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
