# Generated by Django 4.2.17 on 2025-02-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0023_hederauser_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
